---
title: "D. coccinellae Multivariate Stats"
author: "Scott Monahann and Trevor Mugoya"
date: "`r Sys.Date()`"
output: pdf
---
# libraries
Load important libraries 
```{r, include=F}
# setwd("/set/path/here")

setwd("/home/trevor/Desktop/SUMMER_2024/WASP/D_coccinellae_Paper")
library(corrplot)
library(factoextra)
library(vegan)
library(tidyverse)
library(Hmisc)
library(readxl)
# Note: before installing MVN package ensure that libgsl is installed with sudo apt-get install libgsl-dev
library(MVN)
library(heplots)
library(devtools)
# install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
library(pairwiseAdonis)
library(packfor)
library(languageR)
library(multcompView)
library(ggsignif)
library(ggpubr)
library(ggfortify)
library(egg)
# install.packages("egg")
library(tagger)
# devtools::install_github("eliocamp/tagger")
library(rstatix)
# install.packages("ggpmisc")
library(ggpmisc)
```
# Data Import

```{r}
# Creating seperate dataframes for response(offspring morphology) and predictor(parent morphology and bettle host type) matrices
WaspData=read_excel("DATA/morph_data_bk.xlsx")
offspringwasp<-WaspData[,14:19]
parentwasp<-WaspData[,4:9]
```

# Data Preparation
```{r}
# Center and scale both the morphometrics in the wasp offspring and parent matrices prior to fitting RDA model.
offspring.center<-as.data.frame(scale(offspringwasp, center = T, scale = T))
parent.center<-as.data.frame(scale(parentwasp, center = T,scale = T))
parent.center$parent_host<-WaspData$p.host
parent.center$offspring_host<-WaspData$o.host

# Importing host species data
hostData=read_excel("DATA/morpho_data_analysis.xlsx",sheet="host_size_var_nomissing",col_names=TRUE)
# hostData <- read_excel("DATA/wasp_data.xlsx", sheet = "host_size_var_nomissing", col_names = TRUE)
hostData=subset(hostData,select=c(1,2,8,14,20,26,32,38,44))
hostData=hostData[-c(46:51),]
# hostData=rename(hostData,HostSpecies = HostSpecies...1) This errors out
names(hostData)[names(hostData) == "HostSpecies...1"] <- "HostSpecies"

#Now it's usable 
# View(hostData)
```

# Figure 3.
```{r}
# library(tidyverse)

# Reshape the data to long format
hostData_long <- hostData %>%
  pivot_longer(cols = -HostSpecies, names_to = "variable", values_to = "value")
# Add size column to highlight bars based on size
hostData_long <- hostData_long %>% mutate(Host_Size = ifelse(HostSpecies == "C. septempunctata", "Large", "Small"))

# Create the facet wrap plot
hostData_long$HostSpecies <- factor(hostData_long$HostSpecies, levels = c("C. maculata", "H. convergens", "C. septempunctata"))

# Annotations
# Create a data frame containing annotations for all facets
annotations <- data.frame(
    Host_Size = c("Small", "Small", "Small"),
    value = c(3.5, 2.0, 1.25),
    variable = c("Abdominal Length", "Abdominal Width", "Pronotum Length"),
    label = c("*** P <0.001", "** P <0.01", "* P <0.05")
)
tag_pool <- paste0("3", LETTERS[1:8], ".")
plot <- ggplot(hostData_long, aes(x = HostSpecies, y = value, fill = Host_Size)) +
  geom_boxplot() +
  facet_wrap(~ variable, scales = "free_y") +
  tag_facets(tag_pool = tag_pool) +
  theme(strip.text = element_text(size = 13),
        axis.text.x = element_text(angle = 45, hjust = 1),
  		axis.text.y = element_text(size = 16),  # Increase y-axis text size
        axis.title.x = element_text(size = 16),  # Increase x-axis title size
        axis.title.y = element_text(size = 16),  # Increase y-axis title size
        legend.text = element_text(size = 15),  # Increase legend text size
        legend.title = element_text(size = 18)) +  # Increase legend title size
  labs(x = "Host Species", y = "Length (mm)") +
  scale_fill_discrete(name = "Host Size") +
  scale_fill_manual(values = c("Small" = "#dccc82","Large" = "#b5656e"))+
  geom_signif(
      comparisons = list(c("C. maculata", "H. convergens"), c("C. maculata", "C. septempunctata"), c("H. convergens", "C. septempunctata")),
      map_signif_level = TRUE
   ) +
   geom_text(
       data = annotations, aes(x = Host_Size, y = value, label = label),
       color = "#000000", size = 4, fontface = "italic",
       nudge_x = -0.5
   )

plot

# ggsave("Figure3.x.1.png", plot = plot, width = 14, height = 14, dpi = 300)

```

# Figure 3 condensed
```{r, comparison_function}
comparisons_list <- function(data,
                             x) {
    # creating a dataframe with just the columns of interest
    # make sure the grouping variable x is indeed a factor
    # has no unused levels
    data <-
        dplyr::select(
            .data = data,
            x = !!rlang::enquo(x)
        ) %>%
        dplyr::mutate(
            .data = .,
            x = droplevels(as.factor(x))
        )

    grouplevels <- levels(data$x)
    g1_list <- combn(grouplevels, 2)[1, ]
    g2_list <- combn(grouplevels, 2)[2, ]

    comparisons_list <- lapply(
        1:length(g1_list),
        function(i) {
            c(
                combn(grouplevels, 2)[2, i],
                combn(grouplevels, 2)[1, i]
            )
        }
    )

    return(comparisons_list)
}


comp_list <- comparisons_list(
    data = hostData_long,
    x = variable
)
```

```{r}
# Create the boxplot grouped by the variable column
boxplot <- ggplot(hostData_long, aes(x = variable, y = value, fill = HostSpecies)) +
    geom_boxplot() +
    theme_classic() +
    labs(x = "Body Segment", y = "Length (mm)", fill = "Host Species") +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 12), # Increase x-axis text size
        axis.text.y = element_text(size = 18), # Increase y-axis text size
        axis.title.x = element_text(size = 18), # Increase x-axis title size
        axis.title.y = element_text(size = 18), # Increase y-axis title size
        legend.text = element_text(size = 16), # Increase legend text size
        legend.title = element_text(size = 18) # Increase legend title size
    ) +
    scale_fill_manual(values = c("C. maculata" = "#dccc82", "H. convergens" = "#617bb8", "C. septempunctata" = "#b5646f"))
    geom_signif(
        comparisons = comp_list,
        step_increase = 0.1
    )
boxplot
# Display the plot
print(boxplot)

# Save the figure
ggsave("Figure3.2.png", plot = boxplot, width = 14, height = 14, dpi = 300)

```

# Figure 3 Alternate.
```{r}
# library(tidyverse)

# Reshape the data to long format
hostData_long <- hostData %>%
  pivot_longer(cols = -HostSpecies, names_to = "variable", values_to = "value")
# Add size column to highlight bars based on size
hostData_long <- hostData_long %>% mutate(Host_Size = ifelse(HostSpecies == "C. septempunctata", "Large", "Small"))

# Create the facet wrap plot
hostData_long$HostSpecies <- factor(hostData_long$HostSpecies, levels = c("C. maculata", "H. convergens", "C. septempunctata"))

plot2 <- ggplot(hostData_long, aes(x = HostSpecies, y = value, fill = HostSpecies)) +
  geom_boxplot() +
  facet_wrap(~ variable, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
  		axis.text.y = element_text(size = 16),  # Increase y-axis text size
        axis.title.x = element_text(size = 16),  # Increase x-axis title size
        axis.title.y = element_text(size = 16),  # Increase y-axis title size
        legend.text = element_text(size = 15),  # Increase legend text size
        legend.title = element_text(size = 18)) +  # Increase legend title size
  labs(x = "Host Species", y = "Length (mm)") +
  scale_fill_discrete(name = "Host Species") +
  scale_fill_manual(values = c("C. maculata" = "#dccc82", "H. convergens" = "#dccc82", "C. septempunctata" = "#b5646f")) +
  geom_signif(
      comparisons = list(c("C. maculata", "H. convergens"), c("C. maculata", "C. septempunctata"), c("H. convergens", "C. septempunctata"))
      
  )
#   scale_fill_manual(values = c("C. maculata" = "orange", "H. convergens" = "orange", "C. septempunctata" = "purple"))
plot2
ggsave("Figure3.1.1_alternate.png", plot = plot2, width = 16, height = 14, dpi = 300)

```

# Figure 4

```{r}
# Reshape the data to long format
offspringWasp_long <- WaspData %>%
    select(o.host.sl, o.wl, o.tl, o.td, o.al, o.hd, o.hl, o.ms) %>%
    pivot_longer(cols = -o.host.sl, names_to = "Body_Metric", values_to = "Value")

# define order of facets
offspringWasp_long$Body_Metric <- factor(offspringWasp_long$Body_Metric, levels = c("o.wl","o.tl","o.td","o.al","o.hd","o.hl","o.ms"))

# define order of host size
offspringWasp_long$o.host.sl <- factor(offspringWasp_long$o.host.sl, levels = c("small", "large"))

# Define facet title names
fig4_title_names <- c(
    "o.wl" = "Wing Length", 
    "o.tl" = "Thorax Length", 
    "o.td" = "Thorax Depth", 
    "o.al" = "Abdomen Length", 
    "o.hd" = "Head Depth", 
    "o.hl" = "Head Length", 
    "o.ms" = "Mass"
)

# Create tags for figure facets
tag_pool <- paste0("4", LETTERS[1:7], ".")

fig_4 <- ggplot(
offspringWasp_long, aes(x = o.host.sl, y = Value, fill = o.host.sl)) +
    geom_boxplot() +
    facet_wrap(~ Body_Metric, scales = "free_y", labeller = labeller(Body_Metric = fig4_title_names)) +
    tag_facets(tag_pool = tag_pool) +
    theme(
        strip.text = element_text(size = 13),
  		axis.text.y = element_text(size = 16),  # Increase y-axis text size
        plot.title = element_text(color = "#000000", size = 13),
        tagger.panel.tag.text = element_text(color = "#000000", size = 16),
        axis.title.x = element_text(size = 16),  # Increase x-axis title size
        axis.title.y = element_text(size = 16),  # Increase y-axis title size
        legend.text = element_text(size = 15),  # Increase legend text size
        legend.title = element_text(size = 18)) +  # Increase legend title size
    labs(x = NULL, y = "Length (mm)", fill = "Host Size") +
    scale_fill_manual(labels = c("Small", "Large"), values = c("small" = "#dccc82","large" = "#b5656e")) +
    geom_signif(
        comparisons = list(c("small","large"))
    )
fig_4

# fig_4 + geom_text(
#     data = data.frame(o.host.sl = "large", Value = 0.25, Body_Metric = "o.ms", label = "P = 0.27"),
#     aes(x = o.host.sl, y = Value, label = label),
#     color = "#000000", size = 4, fontface = "italic"
# ) + geom_text(
#     data = data.frame(o.host.sl = "large", Value = 0.25, Body_Metric = "o.al", label = "P = 0.27"),
#     aes(x = o.host.sl, y = Value, label = label),
#     color = "#000000", size = 4, fontface = "italic"
# )+ geom_text(
#     data = data.frame(o.host.sl = "large", Value = 0.25, Body_Metric = "o.hd", label = "P = 0.27"),
#     aes(x = o.host.sl, y = Value, label = label),
#     color = "#000000", size = 4, fontface = "italic"
# )+ geom_text(
#     data = data.frame(o.host.sl = "large", Value = 0.25, Body_Metric = "o.hl", label = "P = 0.27"),
#     aes(x = o.host.sl, y = Value, label = label),
#     color = "#000000", size = 4, fontface = "italic"
# )+ geom_text(
#     data = data.frame(o.host.sl = "large", Value = 0.25, Body_Metric = "o.td", label = "P = 0.27"),
#     aes(x = o.host.sl, y = Value, label = label),
#     color = "#000000", size = 4, fontface = "italic"
# )+ geom_text(
#     data = data.frame(o.host.sl = "large", Value = 0.25, Body_Metric = "o.tl", label = "P = 0.27"),
#     aes(x = o.host.sl, y = Value, label = label),
#     color = "#000000", size = 4, fontface = "italic"
# )+ geom_text(
#     data = data.frame(o.host.sl = "large", Value = 0.25, Body_Metric = "o.wl", label = "P = 0.27"),
#     aes(x = o.host.sl, y = Value, label = label),
#     color = "#000000", size = 4, fontface = "italic"
# )
ggsave("Figure4.png", plot = fig_4, width = 14, height = 14, dpi = 300)

```

# Figure 5
```{r}
# Create a new column denoting multilineal or unilineal lines
# WaspData <- WaspData %>%
#     mutate(lineage = ifelse(p.host == o.host, "Unilineal", "Multilineal"))

# Wing length
# Fit overall regression model
overall_model_wl <- lm(o.wl ~ p.wl, data = WaspData)
overall_intercept_wl <- coef(overall_model_wl)[1]
overall_slope_wl <- coef(overall_model_wl)[2]

# Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_wl, 2))
mutlilineal_slope_annotate <- paste("Slope = 0.4")
unilineal_slope_annotate <- paste("Slope = -0.21")

# Create annotation for overall regression
reg_wl <- paste("y =", round(overall_intercept_wl, 2), "+", round(overall_slope_wl, 2), "x", "R^2 = ", round(summary(overall_model_wl)$r.squared, 2), "\n")

wl_regression_plot <- ggplot(WaspData, aes(x = p.wl, y = o.wl, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Wing Length (mm)", y = "Offspring Wing Length (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    # scale_fill_discrete(name = "Type") +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    ) 

wl_regression_plot <- wl_regression_plot + stat_regline_equation(label.x = 2.6, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
wl_regression_plot <- wl_regression_plot + geom_smooth(aes(x = p.wl, y = o.wl), method = "lm", se = F, color = "black",inherit.aes = FALSE)
wl_regression_plot <- wl_regression_plot + annotate("text", x=2.9, y=3.64, size = 5,label= reg_wl)
wl_regression_plot <- wl_regression_plot + geom_label(aes(x = 2.25, y = 2.85), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
wl_regression_plot <- wl_regression_plot + geom_label(aes(x = 3.5, y = 3.2), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
wl_regression_plot <- wl_regression_plot + geom_label(aes(x = 2.25, y = 3.0), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")
wl_regression_plot
ggsave("Figure5.1.png", plot = wl_regression_plot, width = 14, height = 14, dpi = 300)

# Thorax length
overall_model_tl <- lm(o.tl ~ p.tl, data = WaspData)
overall_intercept_tl <- coef(overall_model_tl)[1]
overall_slope_tl <- coef(overall_model_tl)[2]

# Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_tl, 2))
mutlilineal_slope_annotate <- paste("Slope = 0.13")
unilineal_slope_annotate <- paste("Slope = 0.065")

# Create annotation for overall regression
reg_tl <- paste("y =", round(overall_intercept_tl, 2), "+", round(overall_slope_tl, 2), "x", "R^2 = ", round(summary(overall_model_tl)$r.squared, 2), "\n")

tl_regression_plot <- ggplot(WaspData, aes(x = p.tl, y = o.tl, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Thorax Length (mm)", y = "Offspring Thorax Length (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    # scale_fill_discrete(name = "Type") +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    ) 

tl_regression_plot <- tl_regression_plot + stat_regline_equation(label.x = 1.4, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
tl_regression_plot <- tl_regression_plot + geom_smooth(aes(x = p.tl, y = o.tl), method = "lm", se = F, color = "black", linewidth = 1,inherit.aes = FALSE)
tl_regression_plot <- tl_regression_plot + annotate("text", x = 1.52, y = 1.61, size = 5, label = reg_tl)
tl_regression_plot <- tl_regression_plot + geom_label(aes(x = 1.18, y = 1.39), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
tl_regression_plot <- tl_regression_plot + geom_label(aes(x = 1.2, y = 1.31), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
tl_regression_plot <- tl_regression_plot + geom_label(aes(x = 1.2, y = 1.44), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")
tl_regression_plot
ggsave("Figure5.2.png", plot = tl_regression_plot, width = 14, height = 14, dpi = 300)

# Thorax Depth
overall_model_td <- lm(o.td ~ p.td, data = WaspData)
overall_intercept_td <- coef(overall_model_td)[1]
overall_slope_td <- coef(overall_model_td)[2]

# Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_td, 2))
mutlilineal_slope_annotate <- paste("Slope = 0.24")
unilineal_slope_annotate <- paste("Slope = 0.22")

# Create annotation for overall regression
reg_td <- paste("y =", round(overall_intercept_td, 2), "+", round(overall_slope_td, 2), "x", "R^2 = ", round(summary(overall_model_td)$r.squared, 2), "\n")

td_regression_plot <- ggplot(WaspData, aes(x = p.td, y = o.td, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Thorax Depth (mm)", y = "Offspring Thorax Depth (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    # scale_fill_discrete(name = "Type") +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    )
td_regression_plot <- td_regression_plot + stat_regline_equation(label.x = 0.9, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
td_regression_plot <- td_regression_plot + geom_smooth(aes(x = p.td, y = o.td), method = "lm", se = F, color = "black", inherit.aes = FALSE)
td_regression_plot <- td_regression_plot + annotate("text", x = 1.0, y = 1.19, size = 5, label = reg_td)
td_regression_plot <- td_regression_plot + geom_label(aes(x = 1.2, y = 1.0), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
td_regression_plot <- td_regression_plot + geom_label(aes(x = 0.8, y = 0.83), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
td_regression_plot <- td_regression_plot + geom_label(aes(x = 0.8, y = 0.93), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")
td_regression_plot
ggsave("Figure5.3.png", plot = td_regression_plot, width = 14, height = 14, dpi = 300)

# Abdomen Length
overall_model_al <- lm(o.al ~ p.al, data = WaspData)
overall_intercept_al <- coef(overall_model_al)[1]
overall_slope_al <- coef(overall_model_al)[2]

# Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_al, 2))
mutlilineal_slope_annotate <- paste("Slope = 0.31")
unilineal_slope_annotate <- paste("Slope = 0.42")
# Create annotation for overall regression
reg_al <- paste("y =", round(overall_intercept_al, 2), "+", round(overall_slope_al, 2), "x", "R^2 = ", round(summary(overall_model_al)$r.squared, 2), "\n")

al_regression_plot <- ggplot(WaspData, aes(x = p.al, y = o.al, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Abdomen Length (mm)", y = "Offspring Abdomen Length (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    # scale_fill_discrete(name = "Type") +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    )
al_regression_plot <- al_regression_plot + stat_regline_equation(label.x = 1.69, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
al_regression_plot <- al_regression_plot + geom_smooth(aes(x = p.al, y = o.al), method = "lm", se = F, color = "black", inherit.aes = FALSE)
al_regression_plot <- al_regression_plot + annotate("text", x = 1.87, y = 2.45, size = 5, label = reg_al)
al_regression_plot <- al_regression_plot + geom_label(aes(x = 1.6, y = 1.8), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
al_regression_plot <- al_regression_plot + geom_label(aes(x = 1.7, y = 2.0), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
al_regression_plot <- al_regression_plot + geom_label(aes(x = 2.0, y = 1.9), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")

al_regression_plot

ggsave("Figure5.4.png", plot = al_regression_plot, width = 14, height = 14, dpi = 300)

# Head Depth
overall_model_hd <- lm(o.hd ~ p.hd, data = WaspData)
overall_intercept_hd <- coef(overall_model_hd)[1]
overall_slope_hd <- coef(overall_model_hd)[2]

# Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_hd, 2))
mutlilineal_slope_annotate <- paste("Slope = 0.3")
unilineal_slope_annotate <- paste("Slope = -0.4")
# Create annotation for overall regression
reg_hd <- paste("y =", round(overall_intercept_hd, 2), "+", round(overall_slope_hd, 2), "x", "R^2 = ", round(summary(overall_model_hd)$r.squared, 2), "\n")

hd_regression_plot <- ggplot(WaspData, aes(x = p.hd, y = o.hd, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Head Depth (mm)", y = "Offspring Head Depth (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    # scale_fill_discrete(name = "Type") +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    )

hd_regression_plot <- hd_regression_plot + stat_regline_equation(label.x = 0.62, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
hd_regression_plot <- hd_regression_plot + geom_smooth(aes(x = p.hd, y = o.hd), method = "lm", se = F, color = "black", inherit.aes = FALSE)
hd_regression_plot <- hd_regression_plot + annotate("text", x = 0.672, y = 0.73, size = 5, label = reg_hd)
hd_regression_plot <- hd_regression_plot + geom_label(aes(x = 0.7, y = 0.57), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
hd_regression_plot <- hd_regression_plot + geom_label(aes(x = 0.6, y = 0.52), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")
hd_regression_plot <- hd_regression_plot + geom_label(aes(x = 0.7, y = 0.63), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")

hd_regression_plot
ggsave("Figure5.5.png", plot = hd_regression_plot, width = 14, height = 14, dpi = 300)

# Head Length
overall_model_hl <- lm(o.hl ~ p.hl, data = WaspData)
overall_intercept_hl <- coef(overall_model_hl)[1]
overall_slope_hl <- coef(overall_model_hl)[2]

# Create annotation for overall regression
reg_hl <- paste("y =", round(overall_intercept_hl, 2), "+", round(overall_slope_hl, 2), "x", "R^2 == ", round(summary(overall_model_hl)$r.squared, 2), "\n")
overall_slope_annotate <- paste("Slope = ", round(overall_slope_hl, 2))
mutlilineal_slope_annotate <- paste("Slope = 0.03")
unilineal_slope_annotate <- paste("Slope = 0.3")

hl_regression_plot <- ggplot(WaspData, aes(x = p.hl, y = o.hl, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Head Length (mm)", y = "Offspring Head Length (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    # scale_fill_discrete(name = "Type") +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        strip.text.x = element_text(size = 10, face="bold", colour = "black" ),
        strip.text.y = element_text(size = 10, face="bold", colour = "black"),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    )

hl_regression_plot <- hl_regression_plot + stat_regline_equation(label.x = 0.8, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
hl_regression_plot <- hl_regression_plot + geom_smooth(aes(x = p.hl, y = o.hl), method = "lm", se = F, color = "black", inherit.aes = FALSE)
hl_regression_plot <- hl_regression_plot + annotate("text", x = 0.87, y = 1.015, size = 5, label = reg_hl)
hl_regression_plot <- hl_regression_plot + geom_label(aes(x = 1.0, y = 0.86), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
hl_regression_plot <- hl_regression_plot + geom_label(aes(x = 1.0, y = 0.9), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
hl_regression_plot <- hl_regression_plot + geom_label(aes(x = 0.9, y = 0.825), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")
hl_regression_plot

ggsave("Figure5.6.png", plot = hl_regression_plot, width = 14, height = 14, dpi = 300)

```

```{r, figure_5_condensed}
cond <- ggarrange(wl_regression_plot, 
    tl_regression_plot,
    td_regression_plot,
    al_regression_plot,
    hd_regression_plot,
    hl_regression_plot + rremove("x.text"),
    labels = c("5A.)", "5B.)", "5C.)", "5D.)", "5E.)", "5F.)"),
    ncol = 2,
    nrow = 3
)

ggsave("Figure5.X.png", plot = cond, width = 27, height = 35, dpi = 450)
```

# Figure 6
```{r}
ggplot(data = WaspData, aes(x = p.wl, y = o.wl, color = p.host)) +
    stat_poly_line(se = FALSE) +
    stat_poly_eq(use_label(c("eq", "R2"))) +
    geom_point() +
    geom_smooth(method = lm, se = FALSE) +
    labs(
        x = "Parent Wing Length (mm)",
        y = "Offspring Wing Length (mm)"
        # color = "Type"
    )
```