---
title: "D. coccinellae Multivariate Stats"
author: "Scott Monahann and Trevor Mugoya"
date: "`r Sys.Date()`"
output: pdf
---
# libraries
Load important libraries 
```{r, include=F}
# setwd("/set/path/here")
library(corrplot)
library(factoextra)
library(vegan)
library(tidyverse)
library(Hmisc)
# Note: before installing MVN package ensure that libgsl is installed with sudo apt-get install libgsl-dev
library(MVN)
library(heplots)
library(devtools)
# install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
library(pairwiseAdonis)
library(packfor)
library(languageR)
```
# Data Import

```{r}
# Creating seperate dataframes for response(offspring morphology) and predictor(parent morphology and bettle host type) matrices
WaspData <- read.csv2("DATA/morph_data_bk.csv", sep = ",")
offspringwasp<-WaspData[,14:19]
offspringwasp <- offspringwasp %>% mutate_all(as.numeric)
parentwasp<-WaspData[,4:9]
parentwasp <- parentwasp %>% mutate_all(as.numeric)
```

# Data Preparation
```{r}
# Center and scale both the morphometrics in the wasp offspring and parent matrices prior to fitting RDA model.
offspring.center<-as.data.frame(scale(offspringwasp, center = T, scale = T))
parent.center<-as.data.frame(scale(parentwasp, center = T,scale = T))
parent.center$parent_host<-WaspData$p.host
parent.center$offspring_host<-WaspData$o.host
hostData <- read.csv2("DATA/hostData.csv", sep = ",")
hostData=subset(hostData,select=c(1,2,8,14,20,26,32,38,44))
hostData=hostData[-c(46:51),]
names(hostData)[names(hostData) == "HostSpecies...1"] <- "HostSpecies"

#Now it's usable 
View(hostData)
```


# Full RDA Model
```{r}

# Pairwise correlation in our environmental variables
languageR::pairscor.fnc(parentwasp)
# Full RDA model
wasp.rda<-rda(offspring.center~p.wl+p.tl+p.td+p.al+p.hd+p.hl+parent_host+offspring_host, data=parent.center)
# wasp.rda<-rda(offspring.center~p.wl+p.tl+p.td+p.al+p.hd+p.hl+offspring_host, data=parent.center)

summary(wasp.rda)

# For an RDA we need to test for the significance of 3 things
# Global RDA significance
#  Performs a permutation test with 999 permutations and assess the F value to determine whether it is significant or not
anova.cca(wasp.rda, permutations = 999) #p~0.07 we fail to reject the null hypothesis, the full RDA model with all parent morphological characteristics and parent and offspring hosts is not significant.
# Axis significance
anova.cca(wasp.rda, by = "axis") # none of the axes seem significant.

# Explanatory variable significance i.e by term.
anova.cca(wasp.rda, by = "terms")

# parent abdomen length seems marginally significant term.

# The following function tests whether the order of the explanatory variables is significant
anova.cca(wasp.rda, by = "margin")

# R^2 Value
R2 <- RsquareAdj(wasp.rda)$r.squared
R2 

# Adjusted R^2 Value.
R2adj <- RsquareAdj(wasp.rda)$adj.r.squared
R2adj 


# Final ordination plot for full RDA model
ordiplot(wasp.rda, scaling = 2, type = "none", cex = 10, xlab = "RDA1", ylab = "RDA2", cex.lab = 1.25)
points(wasp.rda, col="darkgrey", cex = 1)
points(wasp.rda, dis="sp", col="#3300ff")
text(wasp.rda, dis="sp", col = "blue")
text(wasp.rda, dis="bp", col="black")

```


# Reduced RDA Model
```{r}
# Make copy of predictor matrix 
parent.center.copy <- (parent.center)

# Create new column to distinguish between unilineal and multilineal setups.
parent.center.copy$setup <- ifelse(parent.center.copy$parent_host == parent.center.copy$offspring_host, "unilineal", "multilineal")

# Step wise reduction of predictors.
step.wasp <- step(wasp.rda, scope = formula(wasp.rda), test = "perm")
summary(step.wasp)
# p.td, p.hd, and offspring_host are the predictors in the best model based on lowest AIC.
vif.cca(step.wasp)
# VIF of predictors is less than 20, therefore we can proceed with the reduced model.
wasp.rda2 <- rda(offspring.center ~ p.td + p.hd + offspring_host, data = parent.center.copy) 
summary(wasp.rda2)
# Inspect for colinearity before creating a simpler model. Note that we are looking for VIF lower than 20.
# All our terms are less than 20, therefore we can proceed with the reduced model.
vif.cca(wasp.rda2)
RsquareAdj(wasp.rda2)$adj.r.squared
sqrt(vif.cca(wasp.rda2))
# Global RDA significance
anova.cca(wasp.rda2, permutations = 9999) #We reject H0
# Axis significance
anova.cca(wasp.rda2, by = "axis")
# Term significance
anova.cca(wasp.rda2, by = "terms")

anova(wasp.rda2, by="terms", permutations = 9999)
```

# Final RDA Ordination Plot
```{r}
# Ordination plot parameter choices to specify RDA axes 1 and 2
final_ord <- ordiplot(wasp.rda2, choices = c(1, 2))
points(wasp.rda2, col = ifelse(parent.center.copy$setup == "unilineal", "blue", "red"))
# points(other, dis="sp", col="#d400ff")
text(wasp.rda2, dis="sp", col = "#d400ff")
# text(other, labels = rownames(parent.center.copy), cex = 0.8)
# text(wasp.rda2, dis="bp", col="black")
legend(2.5,-2, legend = c("unilineal", "multilineal"), col = c("blue", "red"), pch = 1)
ordiellipse(final_ord, groups=parent.center.copy$offspring_host, 
                                   display="sites", 
                                   kind="sd",
                                   col="black",
                                   label=T)
title("RDA Analysis of Combined Unilineal and Multilineal Lines")
```