---
title: "D. coccinellae Figures"
author: "Scott Monahann and Trevor Mugoya"
date: "`r Sys.Date()`"
output: pdf
---
# libraries
Load important libraries 
```{r, include=F}
# setwd("/set/path/here")
library(corrplot)
library(factoextra)
library(vegan)
library(tidyverse)
library(Hmisc)
library(readxl)
# Note: before installing MVN package ensure that libgsl is installed with sudo apt-get install libgsl-dev
library(MVN)
library(heplots)
library(devtools)
library(remotes)
# install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
library(pairwiseAdonis)
library(packfor)
library(languageR)
library(multcompView)
library(ggsignif)
library(ggpubr)
library(ggfortify)
library(egg)
# install.packages("egg")
library(tagger)
# devtools::install_github("eliocamp/tagger")
library(rstatix)
# install.packages("ggpmisc")
library(ggpmisc)
```
# Data Import

```{r}
# Importing wasp morphological data
WaspData <- read.csv2("../DATA/morph_data_bk.csv", sep = ",")
# Importing host species data
hostData <- read.csv2("../DATA/hostData.csv", sep = ",")
```

# Data Preparation
```{r}
WaspData[, c(
  "p.wl", "p.tl", "p.td", "p.al", "p.hd", "p.hl", "p.ms", 
  "o.wl", "o.tl", "o.td", "o.al", "o.hd", "o.hl", "o.ms"
)] <- lapply(
  WaspData[, c(
    "p.wl", "p.tl", "p.td", "p.al", "p.hd", "p.hl", "p.ms", 
    "o.wl", "o.tl", "o.td", "o.al", "o.hd", "o.hl", "o.ms"
  )], 
  as.numeric
)
# Create a new column denoting multilineal or unilineal lines
WaspData <- WaspData %>%
    mutate(lineage = ifelse(p.host == o.host, "Unilineal", "Multilineal"))

# Create seperate dataframes for unilineal and multilineal data
WD_Uni <- WaspData[WaspData$lineage == "Unilineal",]
WD_Multi <- WaspData[WaspData$lineage == "Multilineal",]

# Subset the host species data to include body length, body width, elytron chord length, body depth, pronotum length, pronotum width, abdominal length and abdominal width.
hostData=subset(hostData,select=c(1,2,8,14,20,26,32,38,44))
hostData=hostData[-c(46:nrow(hostData)),]
names(hostData)[names(hostData) == "HostSpecies...1"] <- "HostSpecies"
hostData[, !names(hostData) %in% "HostSpecies"] <- lapply(hostData[, !names(hostData) %in% "HostSpecies"], as.numeric)


# Reshape the data to long format
hostData_long <- hostData %>%
  pivot_longer(cols = -HostSpecies, names_to = "variable", values_to = "value")
# Add size column to highlight bars based on size
hostData_long <- hostData_long %>% mutate(Host_Size = ifelse(HostSpecies == "C. septempunctata", "Large", "Small"))

# Create the facet wrap plot
hostData_long$HostSpecies <- factor(hostData_long$HostSpecies, levels = c("C. maculata", "H. convergens", "C. septempunctata"))

# Rename the facet titles to remove seperating period for better readability
hostData_long <- hostData_long %>%
  mutate(variable = gsub("\\.", " ", variable))


```

# Figure 3.
```{r}
# Annotations
tag_pool <- paste0("3", LETTERS[1:8], ".")
plot <- ggplot(hostData_long, aes(x = HostSpecies, y = value, fill = Host_Size)) +
  geom_boxplot() +
  facet_wrap(~ variable, scales = "free_y") +
  tag_facets(tag_pool = tag_pool) +
  theme(strip.text = element_text(size = 18),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 15),  # Increase x-axis text size
  		axis.text.y = element_text(size = 20),  # Increase y-axis text size
        axis.title.x = element_text(size = 20),  # Increase x-axis title size
        axis.title.y = element_text(size = 25),  # Increase y-axis title size
        legend.text = element_text(size = 20),  # Increase legend text size
        legend.title = element_text(size = 22)) +  # Increase legend title size
  labs(x = "Host Species", y = "Value (mm)") +
  scale_fill_discrete(name = "Host Size") +
  scale_fill_manual(values = c("Small" = "#dccc82","Large" = "#b5656e"))+
  geom_signif(
      comparisons = list(c("C. maculata", "H. convergens"), c("C. maculata", "C. septempunctata"), c("H. convergens", "C. septempunctata")),
      map_signif_level = TRUE
   )

plot

ggsave("Figure3.png", plot = plot, width = 14, height = 14, dpi = 300)

```

# Figure 4
```{r}

# Calculate Wing length Unilineal and Multilineal slopes.
wl_uni_slope <- coef(lm(o.wl ~ p.wl, data = WD_Uni))[2]
wl_multi_slope <- coef(lm(o.wl ~ p.wl, data = WD_Multi))[2]

# Wing length
# Fit overall regression model
overall_model_wl <- lm(o.wl ~ p.wl, data = WaspData)
overall_intercept_wl <- coef(overall_model_wl)[1]
overall_slope_wl <- coef(overall_model_wl)[2]

# Slope Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_wl, 2))
mutlilineal_slope_annotate <- paste("Slope = ",round(wl_multi_slope, 2))
unilineal_slope_annotate <- paste("Slope =", round(wl_uni_slope, 2))

# Create annotation for overall regression
# reg_wl <- paste("y ==", round(overall_intercept_wl, 2), "+", round(overall_slope_wl, 2), "~R^{2} == ", round(summary(overall_model_wl)$r.squared, 2), "\n")

reg_wl <- paste0("y ==", round(overall_intercept_wl, 2), "+", round(overall_slope_wl, 2),"~x","~R^{2} == ", round(summary(overall_model_wl)$r.squared, 2), "\n")

# reg_wl <- expression(paste("y = ", round(overall_intercept_wl, 2), "+", round(overall_slope_wl, 2),"x", "~ R"^2, " = ", round(summary(overall_model_wl)$r.squared, 2)))

wl_regression_plot <- ggplot(WaspData, aes(x = p.wl, y = o.wl, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Wing Length (mm)", y = "Offspring Wing Length (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    ) 

wl_regression_plot <- wl_regression_plot + stat_regline_equation(label.x = 2.6, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
wl_regression_plot <- wl_regression_plot + geom_smooth(aes(x = p.wl, y = o.wl), method = "lm", se = F, color = "black",inherit.aes = FALSE)
wl_regression_plot <- wl_regression_plot + geom_text(aes(x = 2.907, y = 3.6), size = 5, label = reg_wl, inherit.aes = T, color = "black", parse = T)
wl_regression_plot <- wl_regression_plot + geom_label(aes(x = 2.25, y = 2.85), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
wl_regression_plot <- wl_regression_plot + geom_label(aes(x = 3.5, y = 3.2), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
wl_regression_plot <- wl_regression_plot + geom_label(aes(x = 2.25, y = 3.0), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")
wl_regression_plot
# ggsave("Figure4.1.png", plot = wl_regression_plot, width = 2, height = 2, scale = 5,dpi = 400)

# Thorax length
# Calculate Thorax length Unilineal and Multilineal slopes.
tl_uni_slope <- coef(lm(o.tl ~ p.tl, data = WD_Uni))[2]
tl_multi_slope <- coef(lm(o.tl ~ p.tl, data = WD_Multi))[2]

overall_model_tl <- lm(o.tl ~ p.tl, data = WaspData)
overall_intercept_tl <- coef(overall_model_tl)[1]
overall_slope_tl <- coef(overall_model_tl)[2]

# Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_tl, 2))
mutlilineal_slope_annotate <- paste("Slope = ",round(tl_multi_slope, 2))
unilineal_slope_annotate <- paste("Slope = ",round(tl_uni_slope, 2))

# Create annotation for overall regression
reg_tl <- paste("y ==", round(overall_intercept_tl, 2), "+", round(overall_slope_tl, 2),"~x", "~R^{2} == ", round(summary(overall_model_tl)$r.squared, 2), "\n")

# reg_wl <- paste("y ==", round(overall_intercept_wl, 2), "+", round(overall_slope_wl, 2), "~R^{2} == ", round(summary(overall_model_wl)$r.squared, 2), "\n")


tl_regression_plot <- ggplot(WaspData, aes(x = p.tl, y = o.tl, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Thorax Length (mm)", y = "Offspring Thorax Length (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    ) 

tl_regression_plot <- tl_regression_plot + stat_regline_equation(label.x = 1.4, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
tl_regression_plot <- tl_regression_plot + geom_smooth(aes(x = p.tl, y = o.tl), method = "lm", se = F, color = "black", linewidth = 1,inherit.aes = FALSE)

tl_regression_plot <- tl_regression_plot + geom_text(aes(x = 1.513, y = 1.59), size = 5, label = reg_tl, inherit.aes = T, color = "black", parse = T)

tl_regression_plot <- tl_regression_plot + geom_label(aes(x = 1.18, y = 1.39), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
tl_regression_plot <- tl_regression_plot + geom_label(aes(x = 1.2, y = 1.31), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
tl_regression_plot <- tl_regression_plot + geom_label(aes(x = 1.2, y = 1.44), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")
tl_regression_plot
ggsave("Figure4.2.png", plot = tl_regression_plot, width = 2, height = 2, scale = 5, dpi = 400)

# Thorax Depth
# Calculate Thorax Depth Unilineal and Multilineal slopes.
td_uni_slope <- coef(lm(o.td ~ p.td, data = WD_Uni))[2]
td_multi_slope <- coef(lm(o.td ~ p.td, data = WD_Multi))[2]

overall_model_td <- lm(o.td ~ p.td, data = WaspData)
overall_intercept_td <- coef(overall_model_td)[1]
overall_slope_td <- coef(overall_model_td)[2]

# Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_td, 2))
mutlilineal_slope_annotate <- paste("Slope = ",round(td_multi_slope, 2))
unilineal_slope_annotate <- paste("Slope = ",round(td_uni_slope, 2))

# Create annotation for overall regression
reg_td <- paste("y ==", round(overall_intercept_td, 2), "+", round(overall_slope_td, 2), "~x", "~R^{2} == ", round(summary(overall_model_td)$r.squared, 2), "\n")

td_regression_plot <- ggplot(WaspData, aes(x = p.td, y = o.td, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Thorax Depth (mm)", y = "Offspring Thorax Depth (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    )
td_regression_plot <- td_regression_plot + stat_regline_equation(label.x = 0.9, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
td_regression_plot <- td_regression_plot + geom_smooth(aes(x = p.td, y = o.td), method = "lm", se = F, color = "black", inherit.aes = FALSE)
td_regression_plot <- td_regression_plot + geom_text(aes(x = 0.996, y = 1.17), size = 5, label = reg_td, inherit.aes = T, color = "black", parse = T)
td_regression_plot <- td_regression_plot + geom_label(aes(x = 1.05, y = 1.0), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
td_regression_plot <- td_regression_plot + geom_label(aes(x = 0.8, y = 0.83), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
td_regression_plot <- td_regression_plot + geom_label(aes(x = 0.8, y = 0.93), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")
td_regression_plot
# ggsave("/home/tmugoya/Desktop/Figure4.3.png", plot = td_regression_plot, width = 2, height = 2, scale = 5, , dpi = 400)

# Abdomen Length
# Calculate abdominal length Unilineal and Multilineal slopes.
al_uni_slope <- coef(lm(o.al ~ p.al, data = WD_Uni))[2]
al_multi_slope <- coef(lm(o.al ~ p.al, data = WD_Multi))[2]

overall_model_al <- lm(o.al ~ p.al, data = WaspData)
overall_intercept_al <- coef(overall_model_al)[1]
overall_slope_al <- coef(overall_model_al)[2]

# Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_al, 2))
mutlilineal_slope_annotate <- paste("Slope = ",round(al_multi_slope, 2))
unilineal_slope_annotate <- paste("Slope = ",round(al_uni_slope, 2))

# Create annotation for overall regression
reg_al <- paste("y ==", round(overall_intercept_al, 2), "+", round(overall_slope_al, 2), "~x","~R^{2} == ", round(summary(overall_model_al)$r.squared, 2), "\n")


al_regression_plot <- ggplot(WaspData, aes(x = p.al, y = o.al, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Abdomen Length (mm)", y = "Offspring Abdomen Length (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    )
al_regression_plot <- al_regression_plot + stat_regline_equation(label.x = 1.69, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
al_regression_plot <- al_regression_plot + geom_smooth(aes(x = p.al, y = o.al), method = "lm", se = F, color = "black", inherit.aes = FALSE)
al_regression_plot <- al_regression_plot + geom_text(aes(x = 1.895, y = 2.4), size = 5, label = reg_al, inherit.aes = T, color = "black", parse = T)
al_regression_plot <- al_regression_plot + geom_label(aes(x = 1.6, y = 1.8), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
al_regression_plot <- al_regression_plot + geom_label(aes(x = 1.7, y = 2.0), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
al_regression_plot <- al_regression_plot + geom_label(aes(x = 2.0, y = 1.9), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")

al_regression_plot

# ggsave("/home/tmugoya/Desktop/Figure4.4.png", plot = al_regression_plot, width = 2, height = 2, scale = 5, dpi = 400)

# Head Depth
# Calculate Thorax length Unilineal and Multilineal slopes.
hd_uni_slope <- coef(lm(o.hd ~ p.hd, data = WD_Uni))[2]
hd_multi_slope <- coef(lm(o.hd ~ p.hd, data = WD_Multi))[2]

overall_model_hd <- lm(o.hd ~ p.hd, data = WaspData)
overall_intercept_hd <- coef(overall_model_hd)[1]
overall_slope_hd <- coef(overall_model_hd)[2]

# Annotations
overall_slope_annotate <- paste("Slope = ", round(overall_slope_hd, 2))
mutlilineal_slope_annotate <- paste("Slope = ",round(hd_multi_slope, 2))
unilineal_slope_annotate <- paste("Slope = ",round(hd_uni_slope, 2))
# Create annotation for overall regression
reg_hd <- paste("y ==", round(overall_intercept_hd, 2), "+", round(overall_slope_hd, 2), "~x", "~R^{2} == ", round(summary(overall_model_hd)$r.squared, 2), "\n")

hd_regression_plot <- ggplot(WaspData, aes(x = p.hd, y = o.hd, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Head Depth (mm)", y = "Offspring Head Depth (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    )

hd_regression_plot <- hd_regression_plot + stat_regline_equation(label.x = 0.62, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
hd_regression_plot <- hd_regression_plot + geom_smooth(aes(x = p.hd, y = o.hd), method = "lm", se = F, color = "black", inherit.aes = FALSE)
hd_regression_plot <- hd_regression_plot + geom_text(aes(x = 0.6784, y = 0.726), size = 5, label = reg_hd, inherit.aes = T, color = "black", parse = T)
hd_regression_plot <- hd_regression_plot + geom_label(aes(x = 0.7, y = 0.57), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
hd_regression_plot <- hd_regression_plot + geom_label(aes(x = 0.6, y = 0.52), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")
hd_regression_plot <- hd_regression_plot + geom_label(aes(x = 0.7, y = 0.63), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")

hd_regression_plot
# ggsave("/home/tmugoya/Desktop/Figure4.5.png", plot = hd_regression_plot, width = 2, height = 2, scale = 5, dpi = 400)

# Head Length
# Calculate Thorax length Unilineal and Multilineal slopes.
hl_uni_slope <- coef(lm(o.hl ~ p.hl, data = WD_Uni))[2]
hl_multi_slope <- coef(lm(o.hl ~ p.hl, data = WD_Multi))[2]

overall_model_hl <- lm(o.hl ~ p.hl, data = WaspData)
overall_intercept_hl <- coef(overall_model_hl)[1]
overall_slope_hl <- coef(overall_model_hl)[2]

# Create annotation for overall regression
reg_hl <- paste("y ==", round(overall_intercept_hl, 2), "+", round(overall_slope_hl, 2), "~x", "~R^{2} == ", round(summary(overall_model_hl)$r.squared, 2), "\n")


overall_slope_annotate <- paste("Slope = ", round(overall_slope_hl, 2))
mutlilineal_slope_annotate <- paste("Slope = ",round(hl_multi_slope, 2))
unilineal_slope_annotate <- paste("Slope = ",round(hl_uni_slope, 2))

hl_regression_plot <- ggplot(WaspData, aes(x = p.hl, y = o.hl, color = lineage)) +
    geom_point(size = 3) +
    theme_classic() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Parent Head Length (mm)", y = "Offspring Head Length (mm)", color = "Type") +
    scale_color_manual(values = c("Unilineal" = "red", "Multilineal" = "blue")) +
    theme(
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
    )

hl_regression_plot <- hl_regression_plot + stat_regline_equation(label.x = 0.8, size = 5, aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")))
hl_regression_plot <- hl_regression_plot + geom_smooth(aes(x = p.hl, y = o.hl), method = "lm", se = F, color = "black", inherit.aes = FALSE)
hl_regression_plot <- hl_regression_plot + geom_text(aes(x = 0.869, y = 1.005), size = 5, label = reg_hl, inherit.aes = T, color = "black", parse = T)
hl_regression_plot <- hl_regression_plot + geom_label(aes(x = 1.0, y = 0.86), label = overall_slope_annotate, size = 6, inherit.aes = F, color = "black")
hl_regression_plot <- hl_regression_plot + geom_label(aes(x = 1.0, y = 0.9), label = mutlilineal_slope_annotate, size = 6, inherit.aes = F, color = "blue")
hl_regression_plot <- hl_regression_plot + geom_label(aes(x = 0.9, y = 0.8259), label = unilineal_slope_annotate, size = 6, inherit.aes = F, color = "red")

hl_regression_plot

# ggsave("/home/tmugoya/Desktop/Figure4.6.png", plot = hl_regression_plot, width = 2, height = 2, scale = 5, dpi = 400)

```

```{r, figure_5_condensed}
detach("package:egg", unload=TRUE)

cond <- ggarrange(
    wl_regression_plot,
    tl_regression_plot,
    td_regression_plot,
    al_regression_plot,
    hd_regression_plot,
    hl_regression_plot,
    labels = c("4A.)", "4B.)", "4C.)", "4D.)", "4E.)", "4F.)"),
    vjust = 2.3,
    hjust = -0.07,
    ncol = 2,
    nrow = 3,
    font.label = list(size = 25, color = "black", face = "bold")
)
cond

ggsave("/home/tmugoya/Desktop/Figure_4.condensed.png",
       plot = cond,
       width = 4,
       height = 6,
       scale = 4.6,
       dpi = 400)
```


# Supplementary Figure.
```{r}
# Reshape the data to long format
offspringWasp_long <- WaspData %>%
    select(o.host.sl, o.wl, o.tl, o.td, o.al, o.hd, o.hl, o.ms) %>%
    pivot_longer(cols = -o.host.sl, names_to = "Body_Metric", values_to = "Value")

# define order of facets
offspringWasp_long$Body_Metric <- factor(offspringWasp_long$Body_Metric, levels = c("o.wl","o.tl","o.td","o.al","o.hd","o.hl","o.ms"))

# define order of host size
offspringWasp_long$o.host.sl <- factor(offspringWasp_long$o.host.sl, levels = c("small", "large"))

# Define facet title names
fig_title_names <- c(
    "o.wl" = "Wing Length", 
    "o.tl" = "Thorax Length", 
    "o.td" = "Thorax Depth", 
    "o.al" = "Abdomen Length", 
    "o.hd" = "Head Depth", 
    "o.hl" = "Head Length", 
    "o.ms" = "Mass (g)"
)

# Create tags for figure facets
tag_pool <- paste0("4", LETTERS[1:7], ".")

fig_sup <- ggplot(
offspringWasp_long, aes(x = o.host.sl, y = Value, fill = o.host.sl)) +
    geom_boxplot() +
    facet_wrap(~ Body_Metric, scales = "free_y", labeller = labeller(Body_Metric = fig_title_names)) +
    tag_facets(tag_pool = tag_pool) +
    theme(
        strip.text = element_text(size = 13),
  		axis.text.y = element_text(size = 16),  # Increase y-axis text size
        plot.title = element_text(color = "#000000", size = 13),
        tagger.panel.tag.text = element_text(color = "#000000", size = 16),
        axis.title.x = element_text(size = 16),  # Increase x-axis title size
        axis.title.y = element_text(size = 16),  # Increase y-axis title size
        legend.text = element_text(size = 15),  # Increase legend text size
        legend.title = element_text(size = 18)) +  # Increase legend title size
    labs(x = NULL, y = "Value (mm)", fill = "Host Size") +
    scale_fill_manual(labels = c("Small", "Large"), values = c("small" = "#dccc82","large" = "#b5656e")) +
    geom_signif(
        comparisons = list(c("small","large"))
    )
fig_sup


ggsave("Figure.png", plot = fig_4, width = 14, height = 14, dpi = 300)

```